### ISSUE TITLE
Powering the FLIP board via 6v BEC.

### ISSUE THREAD

**Issue by DmitriySurin** [wernerdaehn/CC3D-CableCam-Controller#28]
My ESC is SKYRC 160. Built-in 6V/3A BEC. Is this OK for FLIP F32 board and signal from hall sensors?

**Comment by wernerdaehn** [comment]
Yes, no problem. Just connect the ESC to the Servo1 connector with all three pins, signal, +5V and GND. The Flip has a power converter built in to deal with every normal BEC voltage from 5V to 7V.
