### ISSUE TITLE
CC3D Mini Revolution

### ISSUE THREAD

**Issue by edwin540** [wernerdaehn/CC3D-CableCam-Controller#3]
Hi,
I need help.
I do not have a button to enter bootloader mode on this board. I bought this board just for this project, I've finished all the hardware and now came to a stop.
Any help would be greatly appreciated.

Thank You.

**Comment by wernerdaehn** [comment]
Do you have a link or a detailed image to the board. I would expect a solder-pad-bridge on the board then.

**Comment by wernerdaehn** [comment]
Any update? Else I close this.
