### ISSUE TITLE
Support using the oDrive encoder as positional source

### ISSUE THREAD

**Issue by wernerdaehn** [wernerdaehn/CC3D-CableCam-Controller#40]
This is actually two stages.
First read the value from the oDrive.
Second, when the CC3D is set to use the oDrive as source, switch to position control altogether.

**Comment by Willyfan** [comment]
Hi Werner, I read your progress about oDrive. Are you working on this project? Or not? How about position control and slipping?

**Comment by Willyfan** [comment]
Hi Werner, some news? I read about positional control, can you give me details?

**Comment by wernerdaehn** [comment]
The current code is working. I would like to test it some more, though.
