### ISSUE TITLE
Aux Channel 2&3

### ISSUE THREAD

**Issue by litrosy** [wernerdaehn/CC3D-CableCam-Controller#44]
Hi @wernerdaehn 
is it possible to add additional aux channels to the controller? I use the existing AUX channel for focus control, and I would use additional channels for aperture and zoom also.
Great job!!!

**Comment by wernerdaehn** [comment]
Difficult. I am running out of Pins and Timers to use.

Can't you use the SBus output?
https://github.com/wernerdaehn/CC3D-CableCam-Controller/blob/master/docs/SBus%20Output%20for%20Gimbal.md

**Comment by litrosy** [comment]
SBus is occupied with gimbal and camera LANC control function already. I have only one left, but I want all three function(zoom, iris and focus) in one place.
