### ISSUE TITLE
Different pinout 

### ISSUE THREAD

**Issue by JanneHoo** [wernerdaehn/CC3D-CableCam-Controller#45]
Hi Werner! Is it possible to change hal sensor connecting points? I have different pinout compared to flip f4 and don't have RSSI pin there. How can I change it to different pin?
![f4-cc3d-revo-flight-controller-wiring-diagram_2](https://user-images.githubusercontent.com/57917566/69083053-08d11800-0a4a-11ea-8826-766794550fb8.jpg)

**Comment by wernerdaehn** [comment]
Sorry, not supported. It is so hard to configure these MCUs in first place, add configurations would make it a nightmare.
Is this the controller you are using? I used it as well, the encoder pins are Servo5 and Servo6.
